# Understanding Positional Encoding

In [11]:
import torch
seq_len = 8
torch.arange(0,seq_len, dtype=torch.float).unsqueeze(0)

tensor([[0., 1., 2., 3., 4., 5., 6., 7.]])

In [7]:
torch.arange(0,seq_len, dtype=torch.float).unsqueeze(0).shape

torch.Size([1, 8])

In [9]:
torch.arange(0,seq_len, dtype=torch.float).shape

torch.Size([8])

In [15]:
import math
d_model = 5
torch.exp(torch.arange(0, d_model,2).float()* (-math.log(10000.0)/d_model))

tensor([1.0000e+00, 2.5119e-02, 6.3096e-04])

In [47]:
position = torch.arange(0,seq_len, dtype=torch.float).unsqueeze(1)

In [48]:
div_term = torch.exp(torch.arange(0, d_model,2).float()*(-math.log(10000.0)/d_model))

In [23]:
5//2

2

In [46]:
d_model = 6

In [44]:
pe = torch.zeros((seq_len, d_model))

In [49]:
pe[:,0::2] = torch.sin(position * div_term)

In [50]:
pe[:, 1::2] = torch.cos(position * div_term)

In [51]:
pe

tensor([[ 0.0000,  1.0000,  0.0000,  1.0000,  0.0000,  1.0000],
        [ 0.8415,  0.5403,  0.0464,  0.9989,  0.0022,  1.0000],
        [ 0.9093, -0.4161,  0.0927,  0.9957,  0.0043,  1.0000],
        [ 0.1411, -0.9900,  0.1388,  0.9903,  0.0065,  1.0000],
        [-0.7568, -0.6536,  0.1846,  0.9828,  0.0086,  1.0000],
        [-0.9589,  0.2837,  0.2300,  0.9732,  0.0108,  0.9999],
        [-0.2794,  0.9602,  0.2749,  0.9615,  0.0129,  0.9999],
        [ 0.6570,  0.7539,  0.3192,  0.9477,  0.0151,  0.9999]])

In [52]:
position.shape, div_term.shape

(torch.Size([8, 1]), torch.Size([3]))

In [53]:
torch.randn(8,1) * torch.randn(3)

tensor([[-3.5198e-01,  1.1797e-01, -6.3331e-03],
        [-3.4401e+00,  1.1530e+00, -6.1897e-02],
        [ 9.7220e-02, -3.2585e-02,  1.7493e-03],
        [ 1.1518e+00, -3.8605e-01,  2.0725e-02],
        [-7.7894e-01,  2.6107e-01, -1.4015e-02],
        [-6.3370e-01,  2.1240e-01, -1.1402e-02],
        [-7.5260e-01,  2.5225e-01, -1.3541e-02],
        [ 3.9262e-01, -1.3159e-01,  7.0643e-03]])

In [60]:
# (8, 1)
#       ----> (8,3)
# (1, 3)
pe = pe.unsqueeze(0)

In [55]:
x = torch.randn(1, 8, 6)

In [63]:
(x + pe[:, :x.shape[1], :]).shape

torch.Size([1, 8, 6])

In [61]:
pe.shape

torch.Size([1, 8, 6])

In [67]:
m = torch.randn(4,6,7,5)
m.transpose(-1,-2).shape

torch.Size([4, 6, 5, 7])

In [66]:
m.shape[-1]

5